/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Aman' at '5/14/16 9:08 AM' with Gradle 2.9
 *
 * @author Aman, @date 5/14/16 9:08 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
